// pages/pricing.js

import React from 'react';

import Head from 'next/head';



import Review from "../components/Review";



const Contact = () => {





  return (
    <>


      <Head>
        <title>TALKIN.AI Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-10 mx-auto max-w-4xl">

        <div className="topnav">
          <div>
            <h1 className="header1 text-2xl md:text-2xl font-bold">Contact Us</h1>
          </div>
        </div>
        <div className="flex flex-col items-center justify-center px-4 py-2">

          <p className="mt-3 text-1xl text-white">
            Ask a Question or Leave a Review
          </p>
        </div>


        <Review />



      </main>

    </>

  )

};




export default Contact;



